apiVersion: v1
kind: Service
metadata:
        name: LBSvc
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 6969
  selector:
    app: MyApp
  type: LoadBalancer
